### ISSUE TITLE
Doesn't work with fresh archcraft premium install

### ISSUE THREAD

**Issue by ghost** [ozanyetkin/archcraft-bspwm-theme#1]
Can you help? 

archcraft-bspwm-theme   git:(main) ✗ ./apply.sh
./apply.sh: line 12: /home/jason/.config/bspwm/themes/archcraft-bspwm-theme/theme.bash: No such file or directory
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
error: The following required arguments were not provided:
    <amount>

USAGE:
    pastel lighten <amount> [color]...

For more information try --help
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
error: The following required arguments were not provided:
    <amount>

USAGE:
    pastel darken <amount> [color]...

For more information try --help
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
sed: can't read /home/jason/.config/bspwm/themes/archcraft-bspwm-theme/polybar/config.ini: No such file or directory
./apply.sh: line 38: /home/jason/.config/bspwm/themes/archcraft-bspwm-theme/polybar/colors.ini: No such file or directory
sed: can't read /home/jason/.config/bspwm/themes/archcraft-bspwm-theme/rofi/shared/fonts.rasi: No such file or directory
./apply.sh: line 84: /home/jason/.config/bspwm/themes/archcraft-bspwm-theme/rofi/shared/colors.rasi: No such file or directory
Failed to connect to the socket.

archcraft-bspwm-theme   git:(main) ✗

**Comment by ozanyetkin** [comment]
Of course! I think you are trying to run apply.sh directly, but what you need to do is to copy all the files into `~/.config/bspwm/themes/` folder and use `super` + `t` shortcut and select the name of the theme
